### ISSUE TITLE
Mate Appearance Properties 1.16: Background changes aren't piked up until new session

### ISSUE THREAD

**Issue by NHOrus** [oz123/mate-de-gentoo#32] opened 2016-11-28 13:26 UTC
When I select new background, it does not change until I relogin.
Same happened in 1.14, but was solvable by killing Caja and letting session manager restart it. No more. It doesn't help.
Flags and emerge --info data
[use_flags.txt](https://github.com/oz123/mate-de-gentoo/files/616353/use_flags.txt)
[emerge.info.txt](https://github.com/oz123/mate-de-gentoo/files/616349/emerge.info.txt)

Where should I look, additionally?

**Comment by oz123** [comment] 2018-11-24 05:26
closing, can't reproduce.

**Closed as completed by oz123** 2018-11-24 05:26 UTC
