### ISSUE TITLE
Mate Power Manager 1.16: With USE=pm-utils does not show charge of Logitech unified devices

### ISSUE THREAD

**Issue by NHOrus** [oz123/mate-de-gentoo#33] opened 2016-12-03 02:28 UTC
With pure upower, PM shows remaining charge level and general status of Logitech wireless devices paired and connected over unified receiver. With upower-pm-utils, this function does not work and PM icon shows only charge of the laptop battery.
Should be noted that in my case charge level of wireless devices is... bogus due to mouse and keyboard working from batteries, not accumulator.

**Comment by oz123** [comment] 2016-12-03 15:26
I thinks you should report this kind of issue to upstream, not to here. I would not know where to begin with to solve that issue.

**Comment by geki-yaba** [comment] 2017-04-30 07:42
This is caused by a driver name change in linux kernel 3.19.

I have to apply a patch[0] to pm-utils udev rule to detect logitech unified receiver devices.
I also opened a bug[1] at b.g.o, but they seem not to care, sadly.

I hope it helps.

[0] https://github.com/geki-yaba/gekis-salt-seed/blob/master/xorg-mate-intel/patches/95-upower-csr.rules.patch
[1] https://bugs.gentoo.org/572680

**Comment by oz123** [comment] 2017-04-30 09:12
Maybe you just need to ask for a version bump?

**Comment by oz123** [comment] 2018-11-24 05:26
Closing, not relevant here.

**Closed as completed by oz123** 2018-11-24 05:26 UTC
