### ISSUE TITLE
mate-base/mate-panel-1.26.1 version bump

### ISSUE THREAD

**Issue by joakim-tjernlund** [oz123/mate-de-gentoo#57] opened 2021-10-28 23:56 UTC

**Comment by joakim-tjernlund** [comment] 2021-10-29 00:05
I noticed a SEGV in wnck-applet so I hope 1.26.1 will solve that as there are wnck changes in that one.

**Comment by joakim-tjernlund** [comment] 2021-10-29 00:09
Also noticed that mate-base/mate-applets depends on x11-libs/gtksourceview:3.0 while app-editors/pluma depends on >=x11-libs/gtksourceview-4.0.2

Seems a bit odd they don't have the same deps here?

**Comment by joakim-tjernlund** [comment] 2021-11-08 12:00
Ping? Is this overlay still active?

A heads up, mate-screensaver needs an important fix, now it can blank the monitor so one needs to relogin/reboot to get the monitor back.
Fix on the way in https://github.com/mate-desktop/mate-screensaver/pull/262

**Comment by oz123** [comment] 2021-11-08 14:35
Hi, 
The repo is active and maintained. I have not responded because I am quite busy with other stuff.
A hint: I am on github sponsors now. You can definitely help me here!

**Comment by oz123** [comment] 2021-11-09 22:02
> Also noticed that mate-base/mate-applets depends on x11-libs/gtksourceview:3.0 while app-editors/pluma depends on >=x11-libs/gtksourceview-4.0.2
> 
> Seems a bit odd they don't have the same deps here?

I guess that is because pluma uses newer APIs.

Mate applets still uses old gtksource view: https://github.com/mate-desktop/mate-applets/blob/bb0195c17052309b55c23629e24465e1ef4dc70c/configure.ac#L299

**Comment by oz123** [comment] 2021-11-10 11:39
fixed in https://github.com/oz123/mate-de-gentoo/commit/6c396906283bb725b9632df98e17be9d0933942c

**Closed as completed by oz123** 2021-11-10 11:39 UTC

**Comment by joakim-tjernlund** [comment] 2021-11-10 12:21
Thanks, now I only wait for a new mate-screensaver before trying 1.26 again. Seems upstream are in no hurry release a new version though.

**Comment by oz123** [comment] 2021-11-10 15:24
You can easily apply the patch locally. Check patches under /etc/portage.

**Comment by raveit65** [comment] 2021-11-10 20:14
> Thanks, now I only wait for a new mate-screensaver before trying 1.26 again. Seems upstream are in no hurry release a new version though.

Testing an confirming that (https://github.com/mate-desktop/mate-screensaver/pull/262) fixes your issues would speed up merge and release process.

I am waiting for confirmation before i do a new release, because i can't reproduce the issue for myself with fedora.
